[legends]
KC_EXLM = !
KC_QUES = ?
KC_GT = >
KC_LT = <
KC_HASH = #
KC_PERC = %
KC_AT = @
KC_DLR = $
KC_CIRC = ^
KC_LCBR = {
KC_LPRN = (
KC_LBRC = [
KC_RCBR = }
KC_RPRN = )
KC_RBRC = ]
KC_PIPE = |
KC_GRV = `
KC_TILD = ~
KC_PLUS = +
KC_AMPR = &
KC_UNDS = _
KC_MINS = - /
KC_EQL = =
KC_SLSH = /
KC_COMM = , –
KC_DOT = . •
KC_ASTR = *
KC_BSLS = \
KC_BSLASH = \
KC_QUOT = ' "
KC_COLN = :
KC_SCLN = ;
KC_LABK = <
KC_RABK = >
KC_PSCR = PrintSc
KC_NLCK = NumLock
KC_SLCK = ScrLock
KC_INS = Ins
_ =
__ =

KC_P0 = 0
KC_P1 = 1
KC_P2 = 2
KC_P3 = 3
KC_P4 = 4
KC_P5 = 5
KC_P6 = 6
KC_P7 = 7
KC_P8 = 8
KC_P9 = 9
KC_PAST = *
KC_PSLS = /
KC_PPLS = +
KC_PMNS = -
KC_PDOT = .
KC_PEQL = =

KC_MS_U = MOUSE ↑
KC_MS_D = MOUSE ↓
KC_MS_L = MOUSE ←
KC_MS_R = MOUSE →
KC_WH_U = WHEEL ↑
KC_WH_D = WHEEL ↓
KC_WBAK = ⯬
KC_WFWD = ⯮

C(KC_A) = Ctrl+A
C(KC_B) = Ctrl+B
C(KC_C) = Ctrl+C
C(KC_D) = Ctrl+D
C(KC_E) = Ctrl+E
C(KC_F) = Ctrl+F
C(KC_G) = Ctrl+G
C(KC_H) = Ctrl+H
C(KC_I) = Ctrl+I
C(KC_J) = Ctrl+J
C(KC_K) = Ctrl+K
C(KC_L) = Ctrl+L
C(KC_M) = Ctrl+M
C(KC_N) = Ctrl+N
C(KC_O) = Ctrl+O
C(KC_P) = Ctrl+P
C(KC_Q) = Ctrl+Q
C(KC_R) = Ctrl+R
C(KC_S) = Ctrl+S
C(KC_T) = Ctrl+T
C(KC_U) = Ctrl+U
C(KC_V) = Ctrl+V
C(KC_W) = Ctrl+W
C(KC_X) = Ctrl+X
C(KC_Y) = Ctrl+Y
C(KC_Z) = Ctrl+Z

KC_LGUI = LGUI ◆
KC_RGUI = RGUI ◆
KC_LALT = LALT ⎇
KC_RALT = AltGr
KC_LSFT = LSFT ⇧
KC_RSFT = RSFT ⇧
KC_LCTL = LCTL ⎈
KC_RCTL = RCTL ⎈

HOME_A = A/⎇
HOME_B = B
HOME_C = C
HOME_D = D
HOME_E = E/⇧
HOME_F = F
HOME_G = G
HOME_H = H/⎈
HOME_I = I/◆
HOME_J = J
HOME_K = K
HOME_L = L
HOME_M = M
HOME_N = N/⎇
HOME_O = O
HOME_P = P
HOME_Q = Q
HOME_R = R/⇧
HOME_S = S/⎈
HOME_T = T/◆
HOME_U = U
HOME_V = V
HOME_W = W
HOME_X = X
HOME_Y = Y
HOME_Z = Z

MT_RA_W = W/AltGr
MT_RA_Z = Z/AltGr

SYM_ENT = ⏎/SYM
NAV_SPC = ␣/NAV
SYM_TAB = ⇆/SYM
NUM_OSS = ⇧/NUM

OS_LCTL = OS-⎈
OS_LSFT = OS-⇧
OS_LALT = OS-⎇
OS_LGUI = OS-◆
OS_RCTL = OS-⎈
OS_RSFT = OS-⇧
OS_RALT = OS-AltGr
OS_RGUI = OS-◆
OS_HYPR = OS-HYPR
OS_MEH  = OS-MEH

A_UML = Ä
O_UML = Ö
U_UML = Ü
ESZETT = ß
ELLIPS = …
EURO = €
BULLET = •
ENDASH = –
PARAGPH = §

SH_OS = SWAPHNDS
